# permissions for end users to edit hephaestusdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hephaestusdeployment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tmp2
    app.kubernetes.io/part-of: tmp2
    app.kubernetes.io/managed-by: kustomize
  name: hephaestusdeployment-editor-role
rules:
- apiGroups:
  - kubiki.kubiki
  resources:
  - hephaestusdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubiki.kubiki
  resources:
  - hephaestusdeployments/status
  verbs:
  - get
