# permissions for end users to edit testoperartors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: testoperartor-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube2
    app.kubernetes.io/part-of: kube2
    app.kubernetes.io/managed-by: kustomize
  name: testoperartor-editor-role
rules:
- apiGroups:
  - kubiki.kubiki.alpha
  resources:
  - testoperartors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubiki.kubiki.alpha
  resources:
  - testoperartors/status
  verbs:
  - get
