apiVersion: kubiki.kubiki.alpha/v1
kind: HephaestusDeployment
metadata:
  labels:
    app.kubernetes.io/name: hephaestusdeployment
    app.kubernetes.io/instance: hephaestusdeployment-sample
    app.kubernetes.io/part-of: kube2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube2
  name: hephaestusdeployment-sample
spec:
  podImage: "hephaestusmetrics/gui:latest"
